name: Black Duck SARIF Generation
                                                                                                                                                                                                                                          
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
                                                                                                                                                                                                                                          
jobs:
  blackduck-sarif:
    runs-on: ubuntu-latest
                                                                                                                                                                                                                                          
    steps:
    - uses: actions/checkout@v4
                                                                                                                                                                                                                                          
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
                                                                                                                                                                                                                                          
    - name: Install dependencies
      run: |
        cd nodejs-npm
        npm install
                                                                                                                                                                                                                                          
    - name: Black Duck SARIF Scan
      uses: blackducksoftware/blackduck-security-scan-action@v2
      with:
        blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
        blackducksca_reports_sarif_create: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
